/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl1.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.example.mydsl1.T2RuntimeModule
import org.xtext.example.mydsl1.T2StandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class T2IdeSetup extends T2StandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new T2RuntimeModule, new T2IdeModule))
	}
	
}
