/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl1.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.t2.ui.internal.T2Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class T2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return T2Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return T2Activator.getInstance().getInjector(T2Activator.ORG_XTEXT_EXAMPLE_MYDSL1_T2);
	}
	
}
