/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl1.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class T2UiModule extends AbstractT2UiModule {
}
