/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl1.ide;

import org.xtext.example.mydsl1.ide.AbstractT2IdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class T2IdeModule extends AbstractT2IdeModule {
}
