/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl1.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.mydsl1.ui.AbstractT2UiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class T2UiModule extends AbstractT2UiModule {
  public T2UiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
