/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl1.t2.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl1.t2.T2Package;
import org.xtext.example.mydsl1.t2.VAR;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>VAR</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class VARImpl extends MinimalEObjectImpl.Container implements VAR
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VARImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return T2Package.Literals.VAR;
  }

} //VARImpl
