/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl1.t2;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.t2.Value#getDef <em>Def</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.t2.Value#getComp <em>Comp</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.t2.T2Package#getValue()
 * @model
 * @generated
 */
public interface Value extends VAR
{
  /**
   * Returns the value of the '<em><b>Def</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Def</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Def</em>' attribute.
   * @see #setDef(String)
   * @see org.xtext.example.mydsl1.t2.T2Package#getValue_Def()
   * @model
   * @generated
   */
  String getDef();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.t2.Value#getDef <em>Def</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Def</em>' attribute.
   * @see #getDef()
   * @generated
   */
  void setDef(String value);

  /**
   * Returns the value of the '<em><b>Comp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Comp</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comp</em>' attribute.
   * @see #setComp(String)
   * @see org.xtext.example.mydsl1.t2.T2Package#getValue_Comp()
   * @model
   * @generated
   */
  String getComp();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.t2.Value#getComp <em>Comp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comp</em>' attribute.
   * @see #getComp()
   * @generated
   */
  void setComp(String value);

} // Value
