/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl1.t2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>VAR</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl1.t2.T2Package#getVAR()
 * @model
 * @generated
 */
public interface VAR extends EObject
{
} // VAR
