/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl1


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class T2RuntimeModule extends AbstractT2RuntimeModule {
}
