/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl1


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class T2StandaloneSetup extends T2StandaloneSetupGenerated {

	def static void doSetup() {
		new T2StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
