/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl1.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.t2.ui.internal.T2Activator;

public class T2UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return T2Activator.getInstance().getInjector("org.xtext.example.mydsl1.T2");
	}

}
