/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl1;

import org.xtext.example.mydsl1.T2StandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class T2StandaloneSetup extends T2StandaloneSetupGenerated {
  public static void doSetup() {
    new T2StandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
