/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl1.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class T2ProposalProvider extends AbstractT2ProposalProvider {
}
